server:
  BindAddress: 0.0.0.0:8442
upstreamConfig:
  upstreams:
  - id: rabbitmq
    path: /
    uri: https://rabbitmq:15671
injectRequestHeaders:
- name: Authorization
  values:
  - claim: access_token
    prefix: 'Bearer '
providers:
- provider: keycloak-oidc
  id: keycloak-oidc
  clientSecret: nt6pmZMeyrgzYgkg2MLgZQZxLveRMW5M
  clientID: rabbitmq-proxy-client
  code_challenge_method: S256
  scope: openid profile email rabbitmq.tag:administrator
  oidcConfig:
    issuerURL: https://keycloak:8443/realms/test
    insecureSkipNonce: true
    audienceClaims:
        - aud
    emailClaim: email
    userIDClaim: email
