
networks:
  rabbitmq_net:
    name: rabbitmq_net
    external: true

services:
  oauth2-proxy:
    image: bitnami/oauth2-proxy:7.7.1
    networks:
      - rabbitmq_net
    command: --alpha-config /etc/oauth2-proxy/alpha-config.yaml --cookie-secure=true
    volumes:
      - "./:/etc/oauth2-proxy"
      - "../keycloak:/etc/keycloak"      
    environment:
      OAUTH2_PROXY_COOKIE_SECRET: ${OAUTH2_PROXY_COOKIE_SECRET}
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_COOKIE_DOMAINS: ""
      OAUTH2_PROXY_WHITELIST_DOMAINS: "*"
      OAUTH2_PROXY_COOKIE_CSRF_PER_REQUEST: "true"
      OAUTH2_PROXY_COOKIE_CSRF_EXPIRE: "5m"
      OAUTH2_PROXY_REDIRECT_URL: https://oauth2-proxy:8442/oauth2/callback
      OAUTH2_PROXY_TLS_KEY_FILE: /etc/oauth2-proxy/certs/server_oauth2-proxy_key.pem
      OAUTH2_PROXY_TLS_CERT_FILE: /etc/oauth2-proxy/certs/server_oauth2-proxy_certificate.pem
    ports:
      - 8442:443
