version: "3.7"
networks:
  rabbitmq_net:
    name: rabbitmq_net
    external: true

services:
  oauth2-proxy:
    image: bitnami/oauth2-proxy:7.4.0
    networks:
      - rabbitmq_net
    command: --alpha-config /etc/oauth2-proxy/oauth2-proxy.yaml --cookie-secure=false
    volumes:
      - "./alpha-config.yaml:/etc/oauth2-proxy/oauth2-proxy.yaml"
    environment:
      OAUTH2_PROXY_COOKIE_SECRET: ${OAUTH2_PROXY_COOKIE_SECRET}
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_WHITELIST_DOMAINS: "*"
      OAUTH2_PROXY_COOKIE_CSRF_PER_REQUEST: "true"
      OAUTH2_PROXY_COOKIE_CSRF_EXPIRE: "5m"
      OAUTH2_PROXY_REDIRECT_URL: http://0.0.0.0:4180/oauth2/callback
    ports:
      - 4180:4180
