log.console.level = debug

auth_backends.1 = rabbit_auth_backend_oauth2

# Common settings for all resources
auth_oauth2.preferred_username_claims.1 = preferred_username
auth_oauth2.preferred_username_claims.2 = user_name
auth_oauth2.preferred_username_claims.3 = email

# OAuth2 resource for operations whose users are managed by UAA Idp
auth_oauth2.resource_servers.1.id = rabbitmq-4-uaa
auth_oauth2.resource_servers.1.additional_scopes_key = extra_scope
auth_oauth2.resource_servers.1.jwks_url = http://uaa:8080/token_keys

# OAuth2 resource for operations whose users are managed by another Idp
auth_oauth2.resource_servers.2.id = rabbitmq-4-keycloak
auth_oauth2.resource_servers.2.scope_prefix = rabbitmq.
auth_oauth2.resource_servers.2.jwks_url = http://keycloak:8080/realms/test/protocol/openid-connect/certs
